export {
  atualizarQuestao,
  buscarQuestaoPorFiltro,
  buscarQuestaoPorId,
  createQuestion,
  deleteQuestion,
  listProfessorQuestions,
  listarQuestoes,
  listarQuestoesProfessor,
  removerQuestao,
  updateQuestion,
} from './model/questionService';
export type {
  ApiPaginatedResponse,
  ApiQuestionDifficulty,
  ApiQuestionType,
  ApiSuccessResponse,
  ListProfessorQuestionsPayload,
  ListQuestionsResponse,
  PaginationMetadata,
  Question,
  QuestionAlternative,
  ProfessorQuestion,
  QuestionAlternativeKey,
  QuestionAlternatives,
  QuestionDifficulty,
  QuestionFormValues,
  QuestionListParams,
  QuestionStatus,
  QuestionTopic,
  QuestionType,
  SearchQuestionsParams,
  UpdateQuestionPayload,
} from './model/types';
